"""Added is_admin to User

Revision ID: 434022fe34ae
Revises: 
Create Date: 2021-01-10 18:33:05.757583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434022fe34ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
