"""Added Publications

Revision ID: 548b9c3db3a3
Revises: 3b09f06acb8f
Create Date: 2021-01-13 23:30:34.106163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548b9c3db3a3'
down_revision = '3b09f06acb8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('creating_user', sa.String(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updating_user', sa.String(), nullable=False),
    sa.Column('num_reads', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('is_snippet', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_created_date'), 'publications', ['created_date'], unique=False)
    op.create_index(op.f('ix_publications_num_reads'), 'publications', ['num_reads'], unique=False)
    op.create_index(op.f('ix_publications_short_url'), 'publications', ['short_url'], unique=True)
    op.create_index(op.f('ix_publications_updated_date'), 'publications', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_updated_date'), table_name='publications')
    op.drop_index(op.f('ix_publications_short_url'), table_name='publications')
    op.drop_index(op.f('ix_publications_num_reads'), table_name='publications')
    op.drop_index(op.f('ix_publications_created_date'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
