"""Added preview to publications

Revision ID: 58550fc22654
Revises: 548b9c3db3a3
Create Date: 2021-02-01 23:33:28.574026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58550fc22654'
down_revision = '548b9c3db3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('preview', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'preview')
    # ### end Alembic commands ###
